# Generated by Django 4.2.23 on 2025-08-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='菜品名称', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='菜品的详细描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='菜品价格', max_digits=8)),
                ('is_available', models.BooleanField(default=True, help_text='菜品当前是否可售?')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('preparing', '准备中'), ('served', '已上菜'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='订单状态', max_length=20)),
                ('is_paid', models.BooleanField(default=False, help_text='订单是否已支付')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.CharField(help_text='唯一的餐桌号', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('is_available', models.BooleanField(default=True, help_text='餐桌当前是否可用?')),
                ('qr_code', models.ImageField(blank=True, help_text='自动生成的二维码', null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='菜品份数')),
                ('price', models.DecimalField(decimal_places=2, help_text='下单时的菜品单价', max_digits=8)),
                ('menu_item', models.ForeignKey(help_text='具体的菜品', on_delete=django.db.models.deletion.CASCADE, to='core.menuitem')),
                ('order', models.ForeignKey(help_text='所属的订单', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(help_text='订单所属的餐桌', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.table'),
        ),
    ]
