# Generated by Django 4.2.23 on 2025-08-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(help_text='订单所属的餐桌', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.table'),
        ),
    ]
