# Generated by Django 4.2.23 on 2025-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='自动生成的二维码', null=True, upload_to='qr_codes/'),
        ),
    ]
